### ISSUE TITLE
installation issue: greatcirclepath

### ISSUE THREAD

**Issue by jeremiecoullon** [auggiemarignier/pxmcmc#16]
Hello!

I'm trying to install the package from source following the readme, but after running `poetry install` I get the following error:
```
Installing greatcirclepaths (1.1.0): Failed

  KeyError

  "There is no item named 'GreatCirclePaths-1.1.0.dist-info/WHEEL' in the archive"

  at /opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/zipfile.py:1473 in getinfo
      1469│     def getinfo(self, name):
      1470│         """Return the instance of ZipInfo given 'name'."""
      1471│         info = self.NameToInfo.get(name)
      1472│         if info is None:
    → 1473│             raise KeyError(
      1474│                 'There is no item named %r in the archive' % name)
      1475│ 
      1476│         return info
      1477│ 

```

This happens both when using python 3.8 and 3.9, on both OSX 13.4 as well as Ubuntu 18.04.
I'm using poetry version 1.4.0

Have you seen this error before?

Thanks!

**Comment by auggiemarignier** [comment]
Hi @jeremiecoullon,

Very strange, I haven't seen this before and it's weird that it hasn't been picked up in the CI which installs the package from source.

I've just uploaded a new version of `greatcirclepaths` to pypi with an updated deps list so hopefully that will work.  Please give it a try.

Also try simply `pip install greatcirclepaths`.  If that works and `poetry` doesn't then it must be a problem with `poetry`.

**Comment by mattpitkin** [comment]
@auggiemarignier @jeremiecoullon I have been able to get it to install from source on an Ubuntu 20.04 system (within WSL) and using a conda environment. I have done:

```bash
conda create -n pxmcmc python=3.9
conda activate pxmcmc
conda install -c conda-forge gh
pip install poetry
gh repo clone auggiemarignier/pxmcmc
cd pxmcmc
poetry install
```

**Comment by jeremiecoullon** [comment]
I upgraded poetry and it worked; thanks!
