### ISSUE TITLE
Internal version string does not match the package version

### ISSUE THREAD

**Issue by mattpitkin** [auggiemarignier/pxmcmc#17]
The `__version__` string in `__init__.py` (0.1.1) does not match the current package version (0.1.5). You could update this manually and create a new release with the correct version in it, or you might want to switch to an automated version management system such as versioneer or setuptools_scm.

**Comment by auggiemarignier** [comment]
@mattpitkin using `importlib.metadata.version()` in `__init__.py` and version bumping with `poetry version`

https://github.com/auggiemarignier/pxmcmc/pull/15/commits/2acd60b0d339bb755cf8b3fe3f167c1b526ad8ce
