### ISSUE TITLE
quick start examples

### ISSUE THREAD

**Issue by jeremiecoullon** [auggiemarignier/pxmcmc#18]
It might be nice to make the examples even easier to run!

Currently (after pulling the PR changes; are these ready to merge to main?) I had to look in the readme to figure out how to run the earthtopography example, and I ran `poetry run python experiments/earthtopography/main.py --infile experiments/earthtopography/ETOPO1_Ice_hpx_256.fits` from root.

It's not too hard to do, but I'd include the exact line of code to run in the main readme (in root), as well as the line to run the plot following that sampling run.

The idea is to make it trivial to get the package to run a basic example, as this is often the first thing someone might try to do while they're still deciding whether to use your package. 

Maybe also have that line only run for a few iterations (it's currently at 10K) so that the sampling can finish in a few seconds (ie: just to test the whole workflow), so that they can then plot the results.

**Comment by auggiemarignier** [comment]
@jeremiecoullon I've updated the `README.md` for the earthtopography example and reduced the number of iterations to 100.  It takes a minute or two to run `python main.py` but that's needed to see some semblance of positive results in the output map.

I'm keeping all the changes relating to the code from the JOSS reviewers in the same PR #15 . They'll be merged when everyone's happy!
